Repository QudevETH/PycQED_py3, pull requests merged in 2020-03, with the labels that each got.

#31 Bug fix and minor cleanup
  pycqed/measurement/detector_functions.py
  pycqed/measurement/pulse_sequences/single_qubit_tek_seq_elts.py
Labels: bug, enhancement

#34 Enh/close file metadata anav2
  pycqed/analysis_v2/base_analysis.py
  pycqed/analysis_v2/timedomain_analysis.py
Labels: enhancement

#33 Enh/analysis v3 upgrades
  pycqed/analysis/analysis_toolbox.py
  pycqed/analysis/fitting_models.py
  pycqed/analysis_v2/readout_analysis.py
  pycqed/analysis_v2/timedomain_analysis.py
  pycqed/analysis_v3/data_processing.py
  pycqed/analysis_v3/fitting.py
  pycqed/analysis_v3/helper_functions.py
  pycqed/analysis_v3/pipeline_analysis.py
  pycqed/analysis_v3/plotting.py
  pycqed/analysis_v3/processing_pipeline.py
  pycqed/analysis_v3/readme.pdf
  pycqed/analysis_v3/saving.py
  pycqed/instrument_drivers/meta_instrument/qubit_objects/QuDev_transmon.py
  pycqed/measurement/multi_qubit_module.py
  pycqed/measurement/sweep_points.py
Labels: bug, enhancement

#28 Devel/transmon models
  pycqed/simulations/transmon.py
Labels: enhancement

#35 Fixes bugs in the state tomography measurement:
  pycqed/analysis/analysis_toolbox.py
  pycqed/measurement/multi_qubit_module.py
  pycqed/measurement/pulse_sequences/multi_qubit_tek_seq_elts.py
Labels: bug

#36 Bugfix/metadata for multi timestamp
  pycqed/analysis_v2/base_analysis.py
Labels: bug
